language: cpp
sudo: required
dist: trusty
matrix:
  include:
    - compiler: gcc
      env: BUILD_TYPE=Coverage
    - compiler: clang
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install libicu-dev libexpat1-dev
  - if [ "$BUILD_TYPE" = "Coverage" ]; then pip install --user pyyaml cpp-coveralls; fi
script:
  - cmake -DCMAKE_CXX_FLAGS="-Werror" -DCMAKE_BUILD_TYPE=$BUILD_TYPE .
  - make && make test
  - env LC_ALL=ru_RU.UTF-8 scripts/dbmaint.sh
# This check is broken as it depends on collation
#  - git diff --exit-code; echo $?; true
#  - "if ! git diff --exit-code; then echo 'FATAL: run scripts/dbmaint.sh and commit changes'; false; fi"
after_success:
  - if [ "$BUILD_TYPE" = "Coverage" ]; then coveralls -i lib; fi
