# Find ICU
#
# ICU_INCLUDE_DIR
# ICU_LIBRARY
# ICU_FOUND
#

FIND_PATH(ICU_INCLUDE_DIR NAMES unicode/unistr.h)

FIND_LIBRARY(ICU_LIBRARY NAMES icuuc)

INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(ICU DEFAULT_MSG ICU_LIBRARY ICU_INCLUDE_DIR)

MARK_AS_ADVANCED(ICU_INCLUDE_DIR ICU_LIBRARY)
